### PR TITLE
Resolve compilation errors

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by kubukoz** [comment]
A bisect tells me the docs were broken by 1eeceab2ee6e567d863b417c2f7439bc6e880fa7, will take a cloesr look...

**Comment by kubukoz** [comment]
green! I couldn't see the microsite locally without changes (non-empty path prefix), but when I commented that part out, it looks fine:

image
